languageCode = "en-us"
title = "Tardigrade | Decentralized Cloud Object Storage"
paginate = 8

[permalinks]
  partner = "/partner/"
  privacy-policy = "/privacy-policy/"
  storage-sla = "/service-level-commitment/"
  support="/support/"
  terms-of-use = "/terms-of-use/"
  terms-of-service = "/terms-of-service/"
  acceptable-use-policy="/acceptable-use-policy/"
  code-of-conduct = "/code-of-conduct/"
  cookie-policy="/cookie-policy/"
  notice-takedown-policy="/notice-takedown-policy/"
  support-policy="/support-policy/"
  almost-there="/almost-there/"
  community="/community/"
  press-kit="/press-kit/"
  tech-partner = "/tech-partner/"
  thank-you="/thank-you/"
  apps="/apps/"
  partner-form="/partner-form/"
  partner-thank-you="/partner-thank-you/"
  universal-login="/satellites/"
	satellites-verify="/satellites/verify/"
	unsubscribed-emails = "/unsubscribed-emails/"
	unsubscribed-notifications = "/unsubscribed-notifications/"



[taxonomies]
  category = "categories"
