languageCode = "en-us"
title = "Tardigrade"

[permalinks]
  waitlist = "/waitlist/"
  partner = "/partner/"
  privacy-policy = "/privacy-policy/"
  storage-sla = "/service-level-commitment/"
  support="/support/"
  terms-of-use = "/terms-of-use/"
  terms-of-service = "/terms-of-service/"
  acceptable-use-policy="/acceptable-use-policy/"
  code-of-conduct = "/code-of-conduct/"
  cookie-policy="/cookie-policy/"
  notice-takedown-policy="/notice-takedown-policy/"
  support-policy="/support-policy/"
  almost-there="/almost-there/"
  community="/community/"
  tech-partner = "/tech-partner/"
  thank-you="/thank-you/"
  apps="/apps/"
