languageCode = "en-us"
title = "Tardigrade | Decentralized Cloud Object Storage"
description="Get started with durable enterprise-grade cloud storage that's 100% secure, 20% faster, and half the cost of traditional cloud storage."
[permalinks]
  partner = "/partner/"
  privacy-policy = "/privacy-policy/"
  storage-sla = "/service-level-commitment/"
  support="/support/"
  terms-of-use = "/terms-of-use/"
  terms-of-service = "/terms-of-service/"
  acceptable-use-policy="/acceptable-use-policy/"
  code-of-conduct = "/code-of-conduct/"
  cookie-policy="/cookie-policy/"
  notice-takedown-policy="/notice-takedown-policy/"
  support-policy="/support-policy/"
  almost-there="/almost-there/"
  community="/community/"
  tech-partner = "/tech-partner/"
  thank-you="/thank-you/"
  tech-partner-form="/tech-partner-form/"
	os-partner-form="/os-partner-form/"
  os-partner-thank-you="/os-partner-thank-you/"
	tech-partner-thank-you="/tech-partner-thank-you/"
