backend:
  name: github
  repo: storj/Tardigrade.io
  branch: master
  base_url: https://tardigrade.io
  auth_endpoint: /oauth/auth

media_folder: "static/img/"
public_folder: "/img"
publish_mode: editorial_workflow

collections:
  - name: "hero"
    label: "Home-Hero-section"
    folder: "content/home/hero/"
    slug: "{{slug}}"
    fields:
    - {label: "Title", name: "title", widget: "hidden"}
    - {label: "Heading-Left", name: "headingLeft", widget: "string"}
    - {label: "Heading-Right", name: "headingRight", widget: "string"}
    - {label: "Sub-heading-Left", name: "subheadingLeft", widget: "string"}
    - {label: "Sub-heading-Right", name: "subheadingRight", widget: "string"}
    - {label: "Stage", name: "stage", widget: "string"}
    - {label: "Stage-Descriptor", name: "stageDescriptor", widget: "string"}
    - {label: "Powered-By-Image", name: "poweredByIMG", widget: "image"}
    - {label: "Hero-image", name: "heroIMG", widget: "image"}
    - {label: "Benefits-Column-Left", name: "leftBenefitsCol", widget: "list", default : ["Affordable", "Performant", "Resilient",] }
    - {label: "Benefits-Column-Right", name: "rightBenefitsCol", widget: "list", default : ["Secure", "Predictable", "Intuitive",] }                        
    - {label: "Draft", name: "draft", widget: "boolean", default: false}
  - name: "cta"
    label: "Home-CTA-section"
    folder: "content/home/cta/"
    slug: "{{slug}}"
    fields:
    - {label: "Title", name: "title", widget: "hidden"}
    - {label: "Heading", name: "heading", widget: "string"}
    - {label: "Sub-heading", name: "subheading", widget: "string"}
    - {label: "Button-Text", name: "buttonText", widget: "string"}
    - {label: "draft", name: "draft", widget: "boolean", default: false}
  - name : "how-it-works"
    label: "Home-How-It-Works-section"
    folder: "content/home/how-it-works/"
    slug: "{{slug}}"
    fields:
    - {label: "Title", name: "title", widget: "hidden"}
    - {label: "Heading", name: "heading", widget: "string"}
    - {label: "Subheading", name: "subheading", widget: "string"}
    - {label: "Draft", name: "draft", widget: "boolean", default: false}
  - name: "simple-storage-heading"
    label: "Home-Simple-Storage-Section-Heading"
    folder: "content/home/simple-storage/heading/"
    slug: "{{slug}}"
    fields:
    - {label: "Title", name: "title", widget: "hidden"}
    - {label: "Heading-Left", name: "headingLeft", widget: "string"}
    - {label: "Heading-Right", name: "headingRight", widget: "string"}
    - {label: "Draft", name: "draft", widget: "boolean", default: false}
  - name: "simple-storage"
    label: "Home-Simple-Storage-Section-Examples"
    folder: "content/home/simple-storage/examples/"
    slug: "{{slug}}"
    fields:
    - {label: "Title", name: "title", widget: "hidden"}
    - {label: "Heading", name: "heading", widget: "string"}
    - {label: "Image", name: "image", widget: "image"}
    - {label: "Desc", name: "desc", widget: "string"}
    - {label: "class", name: "class", widget: "hidden", default: "simplestorage"}
    - {label: "Draft", name: "draft", widget: "boolean", default: false}
  - name: "why-tardigrade"
    label: "Home-Why-Tardigrade-section-heading"
    folder: "content/home/why-tardigrade/heading/"
    slug: "{{slug}}"
    fields:
    - {label: "title", name: "title", widget: "hidden"}
    - {label: "heading", name: "heading", widget: "string"}
    - {label: "draft", name: "draft", widget: "boolean", default: false}
  - name: "why-tardigrade"
    label: "Home-Why-Tardigrade-Reasons-section"
    folder: "content/home/why-tardigrade/reasons/"
    slug: "{{slug}}"
    fields:
    - {label: "title", name: "title", widget: hidden"}
    - {label: "Image", name: "img", widget: "image"}
    - {label: "Heading", name: "heading", widget: "string"}
    - {label: "Description", name: "desc", widget: "string"}
    - {label: "class", name: "class", widget: "hidden", default: "whytardigrade"}
    - {label: "h", name: "h", widget: "hidden"}
    - {label: "w", name: "w", widget: "hidden"}
    - {label: "weight", name: "weight", widget: "hidden"}
    - {label: "draft", name: "draft", widget: "boolean", default: false}
  - name: "why-tardigrade"
    label: "Home-Why-Tardigrade-CTA"
    folder: "content/home/why-tardigrade/cta/"
    slug: "{{slug}}"
    fields:
    - {label: "title", name: "title", widget: "hidden"}
    - {label: "ctaText", name: "ctaText", widget: "string"}
    - {label: "link", name: "link", widget: "string"}
    - {label: "draft", name: "draft", widget: "boolean", default: false}
  - name: "usecases"
    label: "Home-Usecases-Names-section"
    folder: "content/home/usecases/usecases/"
    slug: "{{slug}}"
    fields:
    - {label: "title", name: "title", widget: "hidden"}
    - {label: "Heading", name: "heading", widget: "string"}
    - {label: "Name", name: "name", widget: "string"}
    - {label: "isActive", name: "isActive", widget: "hidden", default: false}
    - {label: "class", name: "class", widget: "hidden", default: "usecase"}
    - {label: "draft", name: "draft", widget: "boolean", default: false}
  - name: "usecases"
    label: "Home-Usecase-Description-section"
    folder: "content/home/usecases/data-tabs/"
    slug: "{{slug}}"
    fields:
    - {label: "title", name: "title", widget: "hidden"}
    - {label: "Name", name: "name", widget: "string"}
    - {label: "Heading", name: "heading", widget: "string"}
    - {label: "Image", name: "image", widget: "image"}
    - {label: "Description", name: "desc", widget: "string"}
    - {label: "class", name: "class", widget: "hidden", default: "tab"}
    - {label: "isActive", name: "isActive", widget: "hidden", default: false}
    - {label: "draft", name: "draft", widget: "boolean", default: false}
  - name: "milestones"
    label: "Home-Milestones-Heading-section"
    folder: "content/milestones/heading/"
    slug: "{{slug}}"
    fields:
    - {label: "title", name: "title", widget: "hidden"}
    - {label: "Heading", name: "heading", widget: "string"}
    - {label: "Sub-heading-1", name: "subheading1", widget: "string"}
    - {label: "Sub-heading-2", name: "subheading2", widget: "string"}
    - {label: "draft", name: "draft", widget: "boolean", default: false}
  - name: "milestones"
    label: "Home-Milestones-section"
    folder: "content/milestones/milestones"
    slug: "{{slug}}"
    fields:
    - {label: "title", name: "title", widget: "hidden"}
    - {label: "Heading", name: "heading", widget: "string"}
    - {label: "Status", name: "status", widget: "string"}
    - {label: "class", name: "class", widget: "hidden", default: "milestone"}
    - {label: "draft", name: "draft", widget: "boolean", default: false}
  - name: "footer-connect"
    label: "Footer-Connect-Column"
    folder: "content/footer/connect-column/"
    slug: "{{slug}}"
    fields:
    - {label: "title", name: "title", widget: "hidden"}
    - {label: "Link", name: "link", widget: "string"}
    - {label: "Icon", name: "icon", widget: "image"}
    - {label: "weight", name: "weight", widget: "hidden"}
    - {label: "class", name: "class", widget: "hidden", default: "connect"}
    - {label: "draft", name: "draft", widget: "boolean", default: false}
  - name: "footer-product"
    label: "Footer-Product-Column"
    folder: "content/footer/product-column/"
    slug: "{{slug}}"
    fields:
    - {label: "title", name: "title", widget: "hidden"}
    - {label: "Link", name: "link", widget: "string"}
    - {label: "weight", name: "weight", widget: "hidden"}
    - {label: "class", name: "class", widget: "hidden", default: "product"}
    - {label: "draft", name: "draft", widget: "boolean", default: false}
  - name: "footer-resources"
    label: "Footer-Resources-Column"
    folder: "content/footer/resources-column/"
    slug: "{{slug}}"
    fields:
    - {label: "title", name: "title", widget: "hidden"}
    - {label: "Link", name: "link", widget: "string"}
    - {label: "weight", name: "weight", widget: "hidden"}
    - {label: "class", name: "class", widget: "hidden", default: "resources"}
    - {label: "draft", name: "draft", widget: "boolean", default: false}
  - name: "partner-hero"
    label: "Partner-Hero-section"
    folder: "content/partner/headline/"
    slug: "{{slug}}"
    fields: 
    - {label: "title", name: "title", widget: "hidden"}
    - {label: "Heading", name: "heading", widget: "string"}
    - {label: "Content", name: "content", widget: "string"}
    - {label: "Image", name: "img", widget: "image"}
    - {label: "draft", name: "draft", widget: "boolean", default: false}
  - name: "partners"
    label: "Partner-Heading-section"
    folder: "content/partner/partners/"
    slug: "{{slug}}"
    fields: 
    - {label: "title", name: "title", widget: "hidden"}
    - {label: "Heading", name: "heading", widget: "string"}
    - {label: "Content", name: "content", widget: "string"}
    - {label: "draft", name: "draft", widget: "boolean", default: false}
  - name: "partners"
    label: "partners-benefits-heading"
    folder: "content/partner/benefits/"
    slug: "{{slug}}"
    fields: 
    - {label: "title", name: "title", widget: "hidden"}
    - {label: "heading", name: "heading", widget: "string"}
    - {label: "draft", name: "draft", widget: "boolean", default: false}
  - name: "partners"
    label: "Partners-Logo-section"
    folder: "content/partner/benefit-icons/"
    slug: "{{slug}}"
    fields: 
    - {label: "title", name: "title", widget: "hidden"}
    - {label: "Image", name: "img", widget: "image"}
    - {label: "class", name: "class", widget: "hidden", default: "partners"}
    - {label: "weight", name: "weight", widget: "hidden"}
    - {label: "draft", name: "draft", widget: "boolean", default: false}
  - name: "partners"
    label: "Partners-Benefits-section"
    folder: "content/partner/benefit-icons/"
    slug: "{{slug}}"
    fields: 
    - {label: "title", name: "title", widget: "hidden"}
    - {label: "Heading", name: "heading", widget: "string"}
    - {label: "Content", name: "content", widget: "string"}
    - {label: "Image", name: "img", widget: "image"}
    - {label: "class", name: "class", widget: "hidden", default: "benefits"}
    - {label: "weight", name: "weight", widget: "hidden"}
    - {label: "draft", name: "draft", widget: "boolean", default: false}
  - name: "partners-virtuous-cycle"
    label: "Partners-Virtuous-Cycle-section"
    folder: "content/partner/virtuous-cycle/"
    slug: "{{slug}}"
    fields: 
    - {label: "title", name: "title", widget: "hidden"}
    - {label: "heading", name: "heading", widget: "string"}
    - {label: "subheading", name: "subheading", widget: "markdown"}
    - {label: "content1", name: "content1", widget: "markdown"}
    - {label: "content2", name: "content2", widget: "markdown"}
    - {label: "btnLink", name: "btnLink", widget: "string"}
    - {label: "btnText", name: "btnText", widget: "string"}
    - {label: "img", name: "img", widget: "image"}
    - {label: "draft", name: "draft", widget: "boolean", default: false}
  - name: "partners-virtuous-circle-flow"
    label: "partners-virtuous-circle-flow"
    folder: "content/partner/virtuous-circle-icons/"
    slug: "{{slug}}"
    fields: 
    - {label: "title", name: "title", widget: "hidden"}
    - {label: "Heading", name: "heading", widget: "string"}
    - {label: "Image", name: "img", widget: "image"}
    - {label: "class", name: "class", widget: "hidden", default: "virtuous-cycle"}
    - {label: "weight", name: "weight", widget: "hidden"}
    - {label: "draft", name: "draft", widget: "boolean", default: false}
  - name: "waitlist"
    label: "waitlist"
    folder: "content/waitlist/"
    slug: "{{slug}}"
    fields:
    - {label: "title", name: "title", widget: "hidden"}
    - {label: "Heading", name: "heading", widget: "string"}
    - {label: "Sub-heading", name: "subHeading", widget: "string"}
    - {label: "Form-Heading", name: "formHeading", widget: "string"}
    - {label: "Form-Description", name: "formDescription", widget: "string"}
    - {label: "draft", name: "draft", widget: "boolean", default: false}




    

